# pylint: disable=skip-file
{
    'name': 'Extra Employee Info',
    'summary': 'Extra Employee Info',
    'author': "Mohamed Osama, CORE B.P.O",
    'website': "http://www.core-bpo.com",
    'sequence': 1,
    # 'version': '1.0.0',
    'depends': [
        'base',
        'hr',
        'analytic',
        'contact_address',
        'access_tags',
        'hr_attendance',
        'hr_holidays',
        'hr_payroll',
        'hr_employee_insurance',
        'hr_contract',
        'hr_salary_input',
        'website',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/employee_type.xml',
        'views/hr_employee.xml',
        'views/hr_department.xml',
        'views/account_analytic_account.xml',
        'views/hr_office.xml',
        'views/hr_contract.xml',
        'views/hr_payslip.xml',
        'views/hr_attendance.xml',
        # 'views/hr_leave.xml',
        'views/salary_input_line.xml',
        'views/ir_ui_menu.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
