# pylint: disable=skip-file
{
    'name': 'Proposal',
    'summary': 'Proposal',
    'author': "Muhamed Abd El-Rhman, CORE B.P.O",
    'website': "http://www.core-bpo.com",
    'sequence': 1,
    # ADD
    'license': 'LGPL-3',
    # 'version': '1.0.8',
    'depends': [
        'sale',
        'purchase',
        'project',
        'hr_timesheet',
        'project_management',
        'progress_bar',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/proposal_stage.xml',
        'reports/proposal.xml',
        'reports/proposal_claim.xml',
        'wizards/create_rfq.xml',
        'wizards/create_vendor_claim.xml',
        'views/proposal.xml',
        'views/proposal_claim.xml',
        'views/proposal_vendor_claim.xml',
        'views/analytic_account.xml',
        'views/project.xml',
        'views/sale.xml',
        'views/proposal_line.xml',
        'views/proposal_activity_plan.xml',
        'views/proposal_tag.xml',
        'views/proposal_stage.xml',
        'views/proposal_lost_reason.xml',
        'views/proposal_activity_report.xml',
        'views/activity_types.xml',
        'views/account_move.xml',
        'views/purchase.xml',
        'views/proposal_yearly_financial.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
